language: generic
sudo: requried
services:
  - docker

before_install:
  - docker build -t matthewli1409/fdocker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true USERNAME/docker-react npm run test
